<?php
namespace gamboamartin\proceso\models;
use base\orm\_modelo_parent_sin_codigo;

use gamboamartin\administrador\models\adm_seccion;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class pr_entidad_proceso extends _modelo_parent_sin_codigo {
    public function __construct(PDO $link){
        $tabla = 'pr_entidad_proceso';
        $columnas = array($tabla=>false,'adm_seccion'=>$tabla,'pr_proceso'=>$tabla,'pr_tipo_proceso'=>'pr_proceso');
        $campos_obligatorios = array();

        parent::__construct(link: $link,tabla:  $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(array $keys_integra_ds = array('descripcion')): array|stdClass
    {
        $keys = array('pr_proceso_id','adm_seccion_id');
        $valida = $this->validacion->valida_ids(keys: $keys,registro:  $this->registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al validar registro',data: $valida);
        }

        $pr_proceso = (new pr_proceso(link: $this->link))->registro(registro_id: $this->registro['pr_proceso_id'], retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener proceso',data: $pr_proceso);
        }
        $adm_seccion = (new adm_seccion(link: $this->link))->registro(registro_id: $this->registro['adm_seccion_id'], retorno_obj: true);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener adm_seccion',data: $adm_seccion);
        }

        if(!isset($this->registro['codigo'])){
            $codigo = $pr_proceso->pr_proceso_codigo.''.$adm_seccion->adm_seccion_codigo;
            $this->registro['codigo'] = $codigo;
        }
        if(!isset($this->registro['descripcion'])){
            $descripcion = $pr_proceso->pr_proceso_descripcion.''.$adm_seccion->adm_seccion_descripcion;
            $this->registro['descripcion'] = $descripcion;
        }

        $r_alta_bd = parent::alta_bd($keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta registro',data: $r_alta_bd);
        }
        return $r_alta_bd;
    }
}